import '../../core/surge_cipher.dart';

/// User-Agent version fragments, stored obfuscated so the forged Safari
/// version does not sit in the binary as a plaintext literal (and so it can be
/// bumped per project without touching call sites).
/// Generated by `dart run tool/encode_storm_values.dart`.
class AgentMarks {
  const AgentMarks._();

  static const List<int> _osVersionToken = <int>[
    208, 245, 117, 22,
  ];
  static const List<int> _safariVersionToken = <int>[
    208, 245, 4, 22,
  ];

  /// e.g. `18_6` — used inside `CPU iPhone OS <token> like Mac OS X`.
  static String get osVersionToken => SurgeCipher.unscramble(_osVersionToken);

  /// e.g. `18.6` — used inside `Version/<token>`.
  static String get safariVersionToken =>
      SurgeCipher.unscramble(_safariVersionToken);
}
