import '../../core/surge_cipher.dart';

/// Attribution + messaging secrets, stored as obfuscated byte arrays.
/// Generated by `dart run tool/encode_storm_values.dart`.
class BeaconKeys {
  const BeaconKeys._();

  static const List<int> _appsFlyerDevKey = <int>[
    212, 138, 76, 103, 50, 199, 162, 33, 13, 173, 115, 103, 45, 8, 160, 236, 107, 66, 7, 48, 191, 82,
  ];
  static const List<int> _firebaseProjectNumber = <int>[
    214, 255, 27, 17, 97, 151, 246, 98, 9, 219, 114, 1,
  ];

  static String get appsFlyerDevKey =>
      SurgeCipher.unscramble(_appsFlyerDevKey);

  /// GCM_SENDER_ID / Firebase project number, sent as `firebase_project_id`.
  static String get firebaseProjectNumber =>
      SurgeCipher.unscramble(_firebaseProjectNumber);
}
