import '../../core/surge_cipher.dart';

/// Public legal / support pages, stored as obfuscated byte arrays. These must
/// match the URLs registered in App Store Connect and shown in-game.
/// Generated by `dart run tool/encode_storm_values.dart`.
class LegalLinks {
  const LegalLinks._();

  static const List<int> _privacyUrl = <int>[
    137, 185, 94, 80, 38, 153, 234, 116, 72, 152, 47, 70, 45, 47, 181, 252, 99, 92, 55, 88, 138, 10, 24, 143, 212, 160, 253, 102, 40, 78, 91, 107, 81, 244, 249, 96, 245, 102, 211, 241, 248, 115, 217,
  ];
  static const List<int> _supportUrl = <int>[
    137, 185, 94, 80, 38, 153, 234, 116, 72, 152, 47, 70, 45, 47, 181, 252, 99, 92, 55, 88, 138, 10, 24, 143, 215, 167, 228, 96, 38, 95, 86, 104, 73, 239, 248, 101,
  ];

  static String get privacyUrl => SurgeCipher.unscramble(_privacyUrl);
  static String get supportUrl => SurgeCipher.unscramble(_supportUrl);
}
