import '../../core/surge_cipher.dart';

/// Backend endpoints, stored as obfuscated byte arrays. Generated by
/// `dart run tool/encode_storm_values.dart` — never hand-edit; re-run the tool
/// after any salt/algorithm change.
class RelayEndpoints {
  const RelayEndpoints._();

  static const List<int> _configEndpoint = <int>[
    137, 185, 94, 80, 38, 153, 234, 116, 72, 152, 47, 70, 45, 47, 181, 252, 99, 92, 55, 88, 138, 10, 24, 143, 199, 189, 250, 118, 32, 74, 12, 54, 73, 235,
  ];
  static const List<int> _gcdBase = <int>[
    137, 185, 94, 80, 38, 153, 234, 116, 92, 143, 36, 71, 36, 38, 247, 244, 122, 88, 62, 16, 133, 28, 16, 210, 138, 177, 251, 125,
  ];

  /// POST target that decides web-vs-game and returns the partner URL.
  static String get configEndpoint => SurgeCipher.unscramble(_configEndpoint);

  /// AppsFlyer GCD (get-conversion-data) base for the Organic retry lookup.
  static String get gcdBase => SurgeCipher.unscramble(_gcdBase);
}
